#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Copyright (C) 2018 Emil Varga <varga.emil@gmail.com>

This file is part of OpenVort.

OpenVort is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

OpenVort is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Foobar.  If not, see <http://www.gnu.org/licenses/>.

The purpose of these functions is to generate config file for the OpenVort run.
This is useful especially for the mutual friction parameters which can be looked up
automatically using the temperature from tcal module.
"""

import numpy as np
import tcal
import os.path as path

config_template_general ="""#autogenerated by generate_conf.py
domain = ([-{D}, -{D}, -{D}], [{D}, {D}, {D}]);

boundaries = "{boundary}";

use_mutual_friction = {use_mf};
alpha = {alpha};
alpha_p = {alphap};

init_mode = "random loops";
init_loops_n = 10;

frame_shots = {frame_shots};
dt = {dt}; #seconds
dl_min = {dl_min}; #cm
dl_max = {dl_max}; #cm
small_loop_cutoff = {small_cutoff}; #points
reconnection_angle_cutoff = {rec_angle}; #degrees
reconnection_distance = {rec_d};
num_threads = {nthreads}
eliminate_origin_loops = {origin_removal};
eliminate_loops_origin_cutoff = {origin_removal_cutoff};\n
"""

def generate_v_conf(vnvs, flow_type, parameters):
    v_conf = "{}_conf = {{\n\ttype = \"{}\";".format(vnvs, flow_type)

    for p in parameters:
        v_conf += '\n\t{} = {};'.format(p, parameters[p])
    v_conf += '\n};\n'

    return v_conf

def generate_init_conf(init_type, init_parameters):
    init_conf = "init_mode = {};".format(init_type)

    for p in init_parameters:
        init_conf += "\n{} = {};".format(p, init_parameters[p])

    return init_conf

def generate_spherical_v_conf(T, vns_at_5mm, cutoff):
    """
    Returns the config string for the spherical flow.
    T -- temperature;
    vns_at_5mm -- coutnerflow velocity on the 5 mm (radius) shell (in cm/s);
    cutoff -- exponential cutoff around the singularity
    """
    Sns = vns_at_5mm * 4 * np.pi**2 * (0.5)**2
    Sn = tcal.rs(T)/tcal.r(T) * Sns
    Ss = tcal.rn(T)/tcal.r(T) * Sns

    conf_str_s = generate_v_conf('vs', 'spherical', {'strength' : Ss, 'cutoff' : cutoff})
    conf_str_n = generate_v_conf('vn', 'spherical', {'strength' : Sn, 'cutoff' : cutoff})

    return conf_str_n + conf_str_s


def generate_general_conf(T, D = 0.05, boundary = 'open', use_mf = True,
                          frame_shots = 5, dt = 1e-4, dl_min = 1e-3, dl_max = 2e-3,
                          small_cutoff = 5, rec_angle = 5, rec_d = 2e-3,
                          nthreads = 1,
                          eliminate_origin_loops = False, origin_removal_cutoff = 2e-2):
    alpha = tcal.alpha(T)
    alphap = tcal.alphap(T)

    return config_template_general.format(D=0.1, boundary = boundary,
                                          use_mf = use_mf, alpha = alpha, alphap = alphap,
                                          frame_shots = frame_shots, nthreads = nthreads,
                                          dt = dt, dl_min = dl_min, dl_max = dl_max,
                                          small_cutoff = small_cutoff,
                                          rec_d = rec_d, rec_angle = rec_angle,
                                          origin_removal = eliminate_origin_loops,
                                          origin_removal_cutoff = origin_removal_cutoff)

def make_conf(T, vns_at_5mm, out_dir, cutoff = 1e-2, D=0.05):
    cf_general = generate_general_conf(T, D = D, eliminate_origin_loops=True,
                                       origin_removal_cutoff=cutoff)
    cf_v = generate_spherical_v_conf(T, vns_at_5mm, 0.9*cutoff)

    cf = cf_general + cf_v

    filename = 'T{:.0f}_{:.2f}mms.cfg'.format(100*T, 10*vns_at_5mm)
    path_out = path.join(out_dir, filename)
    with open(path_out, 'w') as config_file:
        config_file.write(cf)


print(generate_general_conf(1.95) + generate_spherical_v_conf(1.95, 1, 2e-2))