/*
 * boundary_images.c
 *
 *  Created on: Mar 7, 2018
 *      Author: emil
 *
 *  Generated by the generate_image_tangle_confs.py script in python/ directory
 */


#include "tangle.h"

/*
 * Constant boundary configuration declared in tangle.h
 */

const struct image_tangle periodic_6_img[] = {
    {{-1, 0, 0}, -1},
    {{0, -1, 0}, -1},
    {{0, 0, -1}, -1},
    {{0, 0, 1}, -1},
    {{0, 1, 0}, -1},
    {{1, 0, 0}, -1}
};

const struct image_tangle periodic_18_img[] = {
    {{-1, -1, 0}, -1},
    {{-1, 0, -1}, -1},
    {{-1, 0, 0}, -1},
    {{-1, 0, 1}, -1},
    {{-1, 1, 0}, -1},
    {{0, -1, -1}, -1},
    {{0, -1, 0}, -1},
    {{0, -1, 1}, -1},
    {{0, 0, -1}, -1},
    {{0, 0, 1}, -1},
    {{0, 1, -1}, -1},
    {{0, 1, 0}, -1},
    {{0, 1, 1}, -1},
    {{1, -1, 0}, -1},
    {{1, 0, -1}, -1},
    {{1, 0, 0}, -1},
    {{1, 0, 1}, -1},
    {{1, 1, 0}, -1}
};

const struct image_tangle periodic_26_img[] = {
    {{-1, -1, -1}, -1},
    {{-1, -1, 0}, -1},
    {{-1, -1, 1}, -1},
    {{-1, 0, -1}, -1},
    {{-1, 0, 0}, -1},
    {{-1, 0, 1}, -1},
    {{-1, 1, -1}, -1},
    {{-1, 1, 0}, -1},
    {{-1, 1, 1}, -1},
    {{0, -1, -1}, -1},
    {{0, -1, 0}, -1},
    {{0, -1, 1}, -1},
    {{0, 0, -1}, -1},
    {{0, 0, 1}, -1},
    {{0, 1, -1}, -1},
    {{0, 1, 0}, -1},
    {{0, 1, 1}, -1},
    {{1, -1, -1}, -1},
    {{1, -1, 0}, -1},
    {{1, -1, 1}, -1},
    {{1, 0, -1}, -1},
    {{1, 0, 0}, -1},
    {{1, 0, 1}, -1},
    {{1, 1, -1}, -1},
    {{1, 1, 0}, -1},
    {{1, 1, 1}, -1}
};

const struct image_tangle wall_1_open_img[] = {
    {{0, 0, -1}, Z_L}
};

const struct image_tangle wall_1_6_img[] = {
    {{-1, 0, 0}, -1},
    {{0, -1, 0}, -1},
    {{0, 0, -1}, Z_L},
    {{0, 0, 1}, -1},
    {{0, 1, 0}, -1},
    {{1, 0, 0}, -1}
};

const struct image_tangle wall_1_18_img[] = {
    {{-1, -1, 0}, -1},
    {{-1, 0, -1}, Z_L},
    {{-1, 0, 0}, -1},
    {{-1, 0, 1}, -1},
    {{-1, 1, 0}, -1},
    {{0, -1, -1}, Z_L},
    {{0, -1, 0}, -1},
    {{0, -1, 1}, -1},
    {{0, 0, -1}, Z_L},
    {{0, 0, 1}, -1},
    {{0, 1, -1}, Z_L},
    {{0, 1, 0}, -1},
    {{0, 1, 1}, -1},
    {{1, -1, 0}, -1},
    {{1, 0, -1}, Z_L},
    {{1, 0, 0}, -1},
    {{1, 0, 1}, -1},
    {{1, 1, 0}, -1},
};

const struct image_tangle wall_1_26_img[] = {
    {{-1, -1, -1}, Z_L},
    {{-1, -1, 0}, -1},
    {{-1, -1, 1}, -1},
    {{-1, 0, -1}, Z_L},
    {{-1, 0, 0}, -1},
    {{-1, 0, 1}, -1},
    {{-1, 1, -1}, Z_L},
    {{-1, 1, 0}, -1},
    {{-1, 1, 1}, -1},
    {{0, -1, -1}, Z_L},
    {{0, -1, 0}, -1},
    {{0, -1, 1}, -1},
    {{0, 0, -1}, Z_L},
    {{0, 0, 1}, -1},
    {{0, 1, -1}, Z_L},
    {{0, 1, 0}, -1},
    {{0, 1, 1}, -1},
    {{1, -1, -1}, Z_L},
    {{1, -1, 0}, -1},
    {{1, -1, 1}, -1},
    {{1, 0, -1}, Z_L},
    {{1, 0, 0}, -1},
    {{1, 0, 1}, -1},
    {{1, 1, -1}, Z_L},
    {{1, 1, 0}, -1},
    {{1, 1, 1}, -1}
};

const struct boundary_images open_boundaries = {
    .images = NULL,
    .n = 0
};

const struct boundary_images periodic_6 = {
   .images = periodic_6_img,
   .n = 6
};

const struct boundary_images periodic_18 = {
   .images = periodic_18_img,
   .n = 18
};

const struct boundary_images periodic_26 = {
   .images = periodic_26_img,
   .n = 26
};

const struct boundary_images wall_1_open = {
   .images = wall_1_open_img,
   .n = 1
};

const struct boundary_images wall_1_6 = {
   .images = wall_1_6_img,
   .n = 6
};

const struct boundary_images wall_1_18 = {
   .images = wall_1_18_img,
   .n = 18
};

const struct boundary_images wall_1_26 = {
   .images = wall_1_26_img,
   .n = 26
};
